[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino

upload_port = /dev/cu.usbserial-10
monitor_port = /dev/cu.usbserial-10
monitor_speed = 115200
upload_speed = 115200

build_unflags =
  -std=gnu++11

build_flags =
  -std=gnu++17
  -I include
  -DLV_CONF_INCLUDE_SIMPLE
  -D USER_SETUP_LOADED=1
  -D ILI9486_DRIVER
  -D TFT_WIDTH=320
  -D TFT_HEIGHT=480
  -D TFT_RGB_ORDER=TFT_BGR
  -D TFT_INVERSION_OFF
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_BL=27
  -D TFT_BACKLIGHT_ON=HIGH
  -D TOUCH_CS=33
  -D SPI_FREQUENCY=16000000
  -D SPI_READ_FREQUENCY=16000000
  -D SPI_TOUCH_FREQUENCY=2500000
  -D LOAD_FONT2=1

lib_deps =
  bodmer/TFT_eSPI
  lvgl/lvgl@8.3.11
  paulstoffregen/XPT2046_Touchscreen
  bblanchon/ArduinoJson@6.21.3
